# Generated by Django 5.0.2 on 2024-04-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_category_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transaction_type',
        ),
    ]
