# Generated by Django 5.0.2 on 2024-04-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_category_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transaction_type',
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.category')),
                ('transaction_type', models.CharField(default='expense', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
            bases=('finance.category',),
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.category')),
                ('transaction_type', models.CharField(default='income', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Income Categories',
            },
            bases=('finance.category',),
        ),
    ]
